@STUDY.ASP.ShiftLoggerTryTwo_HostAddress = https://localhost:7128

GET {{STUDY.ASP.ShiftLoggerTryTwo_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{STUDY.ASP.ShiftLoggerTryTwo_HostAddress}}/api/shiftlogger
Content-Type: application/json

{
  //ShiftLogger
}

###
